linters:
  checkstyle:
    config: ./checkstyle.xml
  eslint:
    config: ./eslintrc

files:
  ignore:
    - 'walkthroughs/*'
    - 'tests/*'
    - 'portfolio/src/main/webapp/WEB-INF/*'
    - 'portfolio/pom.xml'
